// examples/ts-lib/src/react-components/Button/index.tsx
import { Button as AntdButton } from 'antd'; // just for testing tsCustomTransformers
import * as React from 'react';

const Button: React.SFC<{
  className?: string;
  onClick?(e: React.MouseEvent<HTMLButtonElement, MouseEvent>): void;
}> = props => {
  const { className = '', children, onClick = () => void 0 } = props;
  return (
    <>
      <button className={`ts-lib-react-button ${className}`} onClick={onClick}>
        {children}
      </button>
      <AntdButton>{children}</AntdButton>
    </>
  );
};

export default Button;

// examples/ts-lib/src/vue-components/Button/button.vue
<template>
  <button class="ts-lib-vue-button" @click="handleClick">
    <slot></slot>
  </button>
</template>

<script lang="js">
import Vue from 'vue'
import { Input } from 'antd'  // just for testing tsCustomTransformers

console.log(Input)

export default {
  name: 'VueButton',
  props: {

  },
  methods: {
    handleClick(e) {
      this.$emit('click', e)
    }
  }
}
</script>
